name: Docker Deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME="yourorg/${{ github.event.repository.name }}"
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          IMAGE_NAME="yourorg/${{ github.event.repository.name }}"
          docker push $IMAGE_NAME:${{ github.sha }}
