
name: Enforce Tagging Rules

on:
  push:
    tags:
      - '*'

jobs:
  validate-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Semver Format
        run: |
          echo "Tag: ${GITHUB_REF##*/}"
          [[ "${GITHUB_REF##*/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
            echo "Invalid tag format. Must follow vX.Y.Z (e.g., v1.2.3)."
            exit 1
          }
